5.0 Static Files & Site Design/project/app1/urls.py
from . import views
from django.urls import path


app_name = 'app1' # name spacing to identify the urls
urlpatterns = [
    path('', views.index, name="index"),
    path('item/', views.item, name="item"),
    path('<int:id>/', views.detail, name="detail"), # the name is used to replace hard coded url in the template
]

5.0 Static Files & Site Design/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls'))

]

5.0 Static Files & Site Design/project/app1/models.py
from django.db import models


# Create your models here.

class Item(models.Model):
    item_name = models.CharField(max_length=200) # max_length is needed
    item_description = models.CharField(max_length=200)
    item_price = models.IntegerField()
    # since it is a link
    item_image = models.CharField(max_length=500, default="https://cdn.dribbble.com/users/1012566/screenshots/4187820/media/3cb974c28eb00627cc0671685c79ffd9.jpg")

    def __str__(self):
        return self.item_name   # allows database to return strings when Item.objects.all()

5.0 Static Files & Site Design/project/app1/views.py
from django.shortcuts import render
from django.http import HttpResponse  # this should be imported
from .models import Item
from django.shortcuts import render


# Create your views here.
def index(request):
    context = {
        'Item_list': Item.objects.all()
    }

    return render(request, "app1/index.html", context)


def item(request):
    Item_list = Item.objects.all()
    context = {
        'Item_list': Item_list,
    }
    return render(request, 'app1/item_list.html', context)


def detail(request, id):
    Item_list = Item.objects.get(pk=id)  # get all by pk
    context = {
        'Item_list': Item_list,
    }

    return render(request, 'app1/detail.html', context)

5.0 Static Files & Site Design/project/app1/templates/app1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app1/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Description</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Price</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      {% block body %}
      {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

5.0 Static Files & Site Design/project/app1/templates/app1/detail.html
{% extends 'app1/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detailed</title>
</head>
<body>
    {% block body %}
    <h1> {{ Item_list.item_name}}</h1>
    <h2>{{ Item_list.item_description}}</h2>
    <h2>{{Item_list.item_price}}</h2>
    {% endblock %}
</body>
</html>

5.0 Static Files & Site Design/project/app1/templates/app1/index.html
{% extends 'app1/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First Django Page</title>
</head>
<body>
    {% block body %}
    <h1> This is a Django Course by Adesina</h1>
    <p>This course is created for my future students, maybe miss Owolabi</p>


    <h1>The data in models</h1>
        {% for item in Item_list %}
            <ul>
                <li>{{item.id}} -- {{item.item_name}} -- {{item.item_description}}--{{item.item_price}} </li>
            </ul>
        {% endfor %}
    {% endblock %}
</body>
</html>

5.0 Static Files & Site Design/project/app1/templates/app1/item_list.html
{% extends 'app1/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First Django Page</title>
</head>
<body>
{% block body%}


    <h1>Click for Detailed View </h1>
        {% for item in Item_list %}
            <ul>
                <li>
                    <a href="{% url 'app1:detail' item.id %}"> {{item.item_name}}</a> <!-- this is how to hide the url-->
                    <img src="{{ item.item_image}}" alt="img" height="150px">
                </li>
            </ul>
        {% endfor %}
{% endblock %}

</body>
</html>